resolver: lts-19.6

packages:
- ./

extra-deps:
- X11-1.10

flags:
  xmonad:
    # stack doesn't support automatic flags
    # https://cabal.readthedocs.io/en/latest/cabal-package.html#resolution-of-conditions-and-flags
    # https://github.com/commercialhaskell/stack/issues/1313#issuecomment-157259270
    quickcheck-classes: false

ghc-options:
    "$everything": -Wwarn
nix:
  packages:
    - zlib
    - xorg.libX11
    - xorg.libXrandr
    - xorg.libXScrnSaver
    - xorg.libXext
